In [13]:
def findDog(input_string):
    a = input_string

    return 'dog' in a

input_str = 'Is there a dog here?'
result = findDog(input_str)

print(result)



False


In [14]:
seg = ['soup', 'dog', 'salad', 'cat', 'great']

filtered_words = list(filter(lambda word: word.startswith('s'), seg))

print(filtered_words)


['soup', 'salad']


In [15]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speed -= 5

    if speed <= 60:
        return 'No Ticket'
    elif 61 <= speed <= 80:
        return 'Small Ticket'
    else:
        return 'Big Ticket'

speed1 = 65
birthday1 = True
result1 = caught_speeding(speed1, birthday1)
print(f"For speed = {speed1}, Birthday = {birthday1}: {result1}")

speed2 = 85
birthday2 = False
result2 = caught_speeding(speed2, birthday2)
print(f"For speed = {speed2}, Birthday = {birthday2}: {result2}")


For speed = 65, Birthday = True: No Ticket
For speed = 85, Birthday = False: Big Ticket


In [2]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speed -= 5

    if speed <= 60:
        return 'No Ticket'
    elif 61 <= speed <= 80:
        return 'Small Ticket'
    else:
        return 'Big Ticket'

speed_input = int(input("Enter the speed: "))
birthday_input = input("Is it your birthday? (yes/no): ").lower()

is_birthday_input = birthday_input == 'yes'

result = caught_speeding(speed_input, is_birthday_input)

print(f"For speed = {speed_input}, Birthday = {is_birthday_input}: {result}")


Enter the speed: 90
Is it your birthday? (yes/no): no
For speed = 90, Birthday = False: Big Ticket


In [14]:
rollNo = int(input("Enter your Roll No. : "))
studentName = (input("Enter your Name : "))
physics = int(input("Marks obtained in Physics : "))
chemistry = int(input("Marks obtained in Chemistry : "))
math = int(input("Marks obtained in Math : "))

totalMarks = physics + chemistry + math;
print("Total Marks :",totalMarks)

percentage = totalMarks/3

if percentage >40 and percentage <=50 :
    print("Pass")
elif percentage >51 and percentage <=60:
    print("Second Class")
elif percentage >61 and percentage <=70:
    print("First Class")
elif percentage >70:
    print("Distinction")     
    
else:
    print("Fail, better luck next time")

Enter your Roll No. : 53
Enter your Name : jefh
Marks obtained in Physics : 90
Marks obtained in Chemistry : 90
Marks obtained in Math : 90
Total Marks : 270
Distinction


In [ ]:
class Student:
    course = 'BCA'
    def __init__(self):
        print('default constructor')
        
    def __init__(self,name,mob):
        self.name=name
        self.mob=mob
        print(name," 's mobile no. is",mob)
        
        

In [11]:
import math



In [9]:
def is_prime(n):
    
 if n <= 1:
   return False
 for i in range(2, int(n**0.5) + 1):
   if n % i == 0:
     return False
 return True

def print_prime_numbers(start, end):

 for num in range(start, end + 1):
   if is_prime(num):
     print(num)

start = 2
end = 50

print(f"Prime numbers between {start} and {end}:")
print_prime_numbers(start, end)

Prime numbers between 2 and 50:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [3]:
num = int(input("Enter a number: "))
l = int(input("Enter the range of the table : "))
print("Multiplication table of", num)

for i in range(1, l+1):
 product = num * i
 print(f"{num} x {i} = {product}")

Enter a number: 11
Enter the range of the table : 7
Multiplication table of 11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77


In [2]:
def fibonacci_recursive(n):

    if n <= 1:
        return n
    else:
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)

nterms = int(input("How many terms? "))

if nterms <= 0:
    print("Please enter a positive integer.")
else:
    print("Fibonacci sequence:")
    for i in range(nterms):
        print(fibonacci_recursive(i))

How many terms? 5
Fibonacci sequence:
0
1
1
2
3


In [52]:
class Employee:
    def __init__(self, empid, name, basic_salary, experience_years):
        self.empid = empid
        self.name = name
        self.basic_salary = basic_salary
        self.experience_years = experience_years
        self.hra = 0
        self.da = 0
        self.pf = 0
        self.bonus = 0
        self.net_salary = 0

    def calculate_hra(self):
        self.hra = 0.35 * self.basic_salary

    def calculate_da(self):
        self.da = 0.58 * self.basic_salary

    def calculate_pf(self):
        self.pf = 0.095 * self.basic_salary

    def calculate_bonus(self):
        if self.experience_years >= 30:
            self.bonus = 0.59 * self.basic_salary
        elif self.experience_years >= 23:
            self.bonus = 0.51 * self.basic_salary
        elif self.experience_years >= 15:
            self.bonus = 0.45 * self.basic_salary
        elif self.experience_years >= 7:
            self.bonus = 0.33 * self.basic_salary
        else:
            self.bonus = 0.16 * self.basic_salary

    def calculate_net_salary(self):
        self.calculate_hra()
        self.calculate_da()
        self.calculate_pf()
        self.calculate_bonus()
        self.net_salary = self.basic_salary + self.da + self.hra - self.pf + self.bonus

if __name__ == '__main__':
    salaryCalc = Employee(10, "vivek", 50000, 30)
    salaryCalc.calculate_net_salary()
    print(f'Net salary is: {salaryCalc.net_salary}')


Net salary is: 121250.0


In [ ]:
n = int(input("Enter Array Length:"))
lst = []
newLst = []
for i in range(0,n):
    newNum = int(input("num:"))
    lst.append(newNum)
print("old List")    
print(lst)
for i in range(0,int(n/2)):
    b=lst[i] + lst[n-1-i]
    newLst.append(b)
print("New List")    
print(newLst)

In [11]:
class Operations:
    def __init__(self, num):
        self.num = num

    def getNum(self):
        return self.num

    def add(self, n2):
        return self.num + n2.num

    def power(self, n2):
        return self.num ** n2.num

    def conca(self, n2):
        return int(str(self.num) + str(n2.num))

    def Max(self, n2):
        return max(self.num, n2.num)

    def Min(self, n2):
        return min(self.num, n2.num)


n1 = Operations(7)
n2 = Operations(3)
print(n1.getNum())

n3 = n1.add(n2)
print(n3)

n3 = n1.power(n2)
print("The Power is:", n3)

n3 = n1.conca(n2)
print("The conca is:", n3)

n3 = n1.Max(n2)
print("The Max is:", n3)

n3 = n1.Min(n2)
print("The Min is:", n3)


7
10
The Power is: 343
The conca is: 73
The Max is: 7
The Min is: 3


In [4]:
Id = [(12345,"Diksha","Diksha@nuv.ac.in"),(4567,"Jiya","Jiya@nuv.ac.in"),
      (6789,"Ronit","Ronit@nuv.ac.in"),(69433,"Heena","Heena@nuv.ac.in")]

#Id_no = int(input("Enter Your ID No. : "))

# name=str(input("enter the name here: "))

email=str(input("enter the email here: "))


# def searchById():
#     for i in range(0,len(Id)):
#         if(Id[i][0]== Id_no):
#             print(Id[i])

# def searchByName():
#     for i in range(0,len(Id)):
#          if(Id[i][1]== name):
#              print(Id[i])

def searchByEmail():
     for i in range(0,len(Id)):
           if(Id[i][2]== email):
               print(Id[i])
            
# searchById()     
# searchByName()
searchByEmail()

enter the email here: Jiya@nuv.ac.in
(4567, 'Jiya', 'Jiya@nuv.ac.in')


In [11]:
# LAB 3 Q.1
enrollment_id = [12345, 45687, 16789, 69433]
student_name = ["Diksha", "Jiva", "Ronit", "Heena"]
email_id = ["Diksha@nuv.ac.in", "Jiya@nuv.ac.in", "Ronit@nuv.ac.in", "Heena@nuv.ac.in"]

student_data = {}

for i in range(len(enrollment_id)):
    student_data[enrollment_id[i]] = {'Student Name': student_name[i], 'Email ID': email_id[i]}

def search_by_id(search_id):
    if search_id in student_data:
        data = student_data[search_id]
        print(f"Student Name: {data['Student Name']}")
        print(f"Email ID: {data['Email ID']}")
    

def search_by_name(search_name):
    found = False
    for enrollment_id, data in student_data.items():
        if data['Student Name'].lower() == search_name.lower():
            found = True
            print(f"Enrollment ID: {enrollment_id}")
            print(f"Email ID: {data['Email ID']}")
   

def search_by_email(search_email):
    found = False
    for enrollment_id, data in student_data.items():
        if data['Email ID'].lower() == search_email.lower():
            found = True
            print(f"Enrollment ID: {enrollment_id}")
            print(f"Student Name: {data['Student Name']}")
    
search_type = input("Enter search type (ID, Name, or Email): ")

if search_type == 'id':
    search_value = int(input("Enter Enrollment ID: "))
    search_by_id(search_value)
elif search_type == 'name':
    search_value = input("Enter Student Name: ")
    search_by_name(search_value)
elif search_type == 'email':
    search_value = input("Enter Email ID: ")
    search_by_email(search_value)

Enter search type (ID, Name, or Email): Name
Enter Student Name: Jiva
Enrollment ID: 45687
Student Name: Jiva
Email ID: Jiya@nuv.ac.in


In [16]:
# LAB 3 Q.2
data = [(12345, "Diksha", "Diksha@nuv.ac.in"), (4567, "Jiya", "Jiya@nuv.ac.in"),
        (6789, "Ronit", "Ronit@nuv.ac.in"), (69433, "Heena", "Heena@nuv.ac.in")]

Dict = {"key 1": [],
        "key 2": [],
        "key 3": []}

for i in data:
    Dict["key 1"].append(i[0])
    Dict["key 2"].append(i[1])
    Dict["key 3"].append(i[2])

print(Dict)


{'key 1': [12345, 4567, 6789, 69433], 'key 2': ['Diksha', 'Jiya', 'Ronit', 'Heena'], 'key 3': ['Diksha@nuv.ac.in', 'Jiya@nuv.ac.in', 'Ronit@nuv.ac.in', 'Heena@nuv.ac.in']}


In [4]:
# LAB 3 Q.3
data = [(12345, "Diksha", "Diksha@nuv.ac.in"), (4567, "Jiya", "Jiya@nuv.ac.in"),
        (6789, "Ronit", "Ronit@nuv.ac.in"), (69433, "Heena", "Heena@nuv.ac.in")]

disc = {
        "ID" : [],
        "Name" : [],
        "Email" : [],
       }
for i in data :
    disc["ID"].append(i[0])
    disc["Name"].append(i[1])
    disc["Email"].append(i[2])
print(disc)   



{'ID': [12345, 4567, 6789, 69433], 'Name': ['Diksha', 'Jiya', 'Ronit', 'Heena'], 'Email': ['Diksha@nuv.ac.in', 'Jiya@nuv.ac.in', 'Ronit@nuv.ac.in', 'Heena@nuv.ac.in']}


In [1]:
# LAB 3 Q.4

import json 
d = {
     "name": "Hina",
     "roll no.": 553,
     "cgpa" : 7.99,
     "phone number" : 123456789,
}
# append data in file
# f = open("BCAStudent.json","a")
# jsondata = json.dump(d,indent=4)
# f.write(jsondata)
# # # to write in file
# f = open("BCAStudent.json","w")
# jsondata = json.dumps(d,indent=4)
# f.write(jsondata)
# read data from file
f = open("BCAStudent.json","r")
jsondata = json.load(f)
print(jsondata)

{'name': 'Hina', 'roll no.': 553, 'cgpa': 7.99, 'phone number': 123456789}


In [4]:
# LAB 3 Q.5

import pandas as pd
df=pd.read_csv("data.csv")
df

StateId           Name   Population in Crore   No. of Universities
0    12001        Gujarat                    10                    29
1    12002    Maharashtra                    19                    36
2    12003      Rajasthan                    13                    31
3    12004  Madhy Pradesh                    14                    21
4    12005         Punjab                    12                    13
5    12006      Karnataka                    23                    31
6    12007      Tamilnadu                    25                    29
7     1208         Kerala                    21                    15

In [11]:

import pandas as pd
df=pd.read_csv("data.csv")
keys = list(df.keys())

value=list(df.values)
print(keys)
states = {}
for d in value:
    states[d[0]]={
        keys[1]:d[1],
        keys[2]:d[2],
        keys[3]:d[3]
    }
    
states    
    

['StateId', ' Name', ' Population in Crore', ' No. of Universities']


{12001: {' Name': 'Gujarat',
  ' Population in Crore': 10,
  ' No. of Universities': 29},
 12002: {' Name': 'Maharashtra',
  ' Population in Crore': 19,
  ' No. of Universities': 36},
 12003: {' Name': 'Rajasthan',
  ' Population in Crore': 13,
  ' No. of Universities': 31},
 12004: {' Name': 'Madhy Pradesh',
  ' Population in Crore': 14,
  ' No. of Universities': 21},
 12005: {' Name': 'Punjab',
  ' Population in Crore': 12,
  ' No. of Universities': 13},
 12006: {' Name': 'Karnataka',
  ' Population in Crore': 23,
  ' No. of Universities': 31},
 12007: {' Name': 'Tamilnadu',
  ' Population in Crore': 25,
  ' No. of Universities': 29},
 1208: {' Name': 'Kerala',
  ' Population in Crore': 21,
  ' No. of Universities': 15}}

In [2]:
import numpy as np


In [4]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
np.zeros(12).reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [7]:
np.eye(5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

NameError: name 'np' is not defined

In [5]:
np.vsplit(mat,3)

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [4]:
mat = np.arange(1,5).reshape(2,2)
mat

array([[1, 2],
       [3, 4]])

In [6]:
np.vsplit(mat,2)

[array([[1, 2]]), array([[3, 4]])]

In [11]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [12]:
np.hsplit(mat,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [15]:
farr=np.random.uniform(1,20,5)

In [16]:
farr

array([ 2.72648691,  9.05466918, 13.27584147,  8.06970081, 19.49558356])

In [17]:
np.ceil(farr)

array([ 3., 10., 14.,  9., 20.])

In [18]:
np.floor(farr)

array([ 2.,  9., 13.,  8., 19.])

In [19]:
np.round(farr,decimals=2)

array([ 2.73,  9.05, 13.28,  8.07, 19.5 ])

mat1 = np.arange(1,26).reshape(5,5)
mat1

In [24]:
far = np.arange(1,26).reshape(5,5)
far

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
np.min(far,axis=0)

array([1, 2, 3, 4, 5])

In [34]:
np.max(far,axis=0)

array([21, 22, 23, 24, 25])

In [35]:
np.std(far,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [37]:
np.arange(0,10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
null_vectors = np.arange(1,11, dtype = float)

In [39]:
null_vectors

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
null_vectors[:]='NAN'

In [41]:
null_vectors

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [42]:
null_vectors[6]=200

In [43]:
null_vectors

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [46]:
dar = np.arange(100,151)

In [47]:
dar

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [48]:
np.flip(dar)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [54]:
a1 = np.array([1,0,2,0,0,4,0, 8])

In [55]:
np.where(a1>0)

(array([0, 2, 5, 7], dtype=int64),)

In [62]:
a2 = np.ones([10,10])

In [64]:
a2[1:9,1:9]=0
a2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])